//
// AddonsDeveloperLink.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AddonsDeveloperLink: Codable {

    public var title: String?
    public var url: String?

    public init(title: String?, url: String?) {
        self.title = title
        self.url = url
    }


}

