//
// V0AppListResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0AppListResponseModel: Codable {

    public var data: [V0AppResponseItemModel]?
    public var paging: V0PagingResponseModel?

    public init(data: [V0AppResponseItemModel]?, paging: V0PagingResponseModel?) {
        self.data = data
        self.paging = paging
    }


}

