//
// V0AppWebhookResponseItemModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0AppWebhookResponseItemModel: Codable {

    public var createdAt: String?
    public var events: String?
    public var headers: String?
    public var registeredByAddon: Bool?
    public var slug: String?
    public var updatedAt: String?
    public var url: String?

    public init(createdAt: String?, events: String?, headers: String?, registeredByAddon: Bool?, slug: String?, updatedAt: String?, url: String?) {
        self.createdAt = createdAt
        self.events = events
        self.headers = headers
        self.registeredByAddon = registeredByAddon
        self.slug = slug
        self.updatedAt = updatedAt
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case createdAt = "created_at"
        case events
        case headers
        case registeredByAddon = "registered_by_addon"
        case slug
        case updatedAt = "updated_at"
        case url
    }

}

