//
// V0AppAddOnResponseItemModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0AppAddOnResponseItemModel: Codable {

    public var _description: String?
    public var documentationUrl: String?
    public var hasUi: Bool?
    public var icon: String?
    public var _id: String?
    public var isBeta: Bool?
    public var plan: AddonsPlan?
    public var setupGuide: AddonsSetupGuide?
    public var summary: String?
    public var title: String?

    public init(_description: String?, documentationUrl: String?, hasUi: Bool?, icon: String?, _id: String?, isBeta: Bool?, plan: AddonsPlan?, setupGuide: AddonsSetupGuide?, summary: String?, title: String?) {
        self._description = _description
        self.documentationUrl = documentationUrl
        self.hasUi = hasUi
        self.icon = icon
        self._id = _id
        self.isBeta = isBeta
        self.plan = plan
        self.setupGuide = setupGuide
        self.summary = summary
        self.title = title
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case documentationUrl = "documentation_url"
        case hasUi = "has_ui"
        case icon
        case _id = "id"
        case isBeta = "is_beta"
        case plan
        case setupGuide = "setup_guide"
        case summary
        case title
    }

}

