//
// V0AppRespModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0AppRespModel: Codable {

    public var slug: String?
    public var status: String?

    public init(slug: String?, status: String?) {
        self.slug = slug
        self.status = status
    }


}

