//
// V0ArtifactListResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0ArtifactListResponseModel: Codable {

    public var data: [V0ArtifactListElementResponseModel]?
    public var paging: V0PagingResponseModel?

    public init(data: [V0ArtifactListElementResponseModel]?, paging: V0PagingResponseModel?) {
        self.data = data
        self.paging = paging
    }


}

