//
// V0ArtifactListElementResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0ArtifactListElementResponseModel: Codable {

    public var artifactMeta: String?
    public var artifactType: String?
    public var fileSizeBytes: Int?
    public var isPublicPageEnabled: Bool?
    public var slug: String?
    public var title: String?

    public init(artifactMeta: String?, artifactType: String?, fileSizeBytes: Int?, isPublicPageEnabled: Bool?, slug: String?, title: String?) {
        self.artifactMeta = artifactMeta
        self.artifactType = artifactType
        self.fileSizeBytes = fileSizeBytes
        self.isPublicPageEnabled = isPublicPageEnabled
        self.slug = slug
        self.title = title
    }

    public enum CodingKeys: String, CodingKey { 
        case artifactMeta = "artifact_meta"
        case artifactType = "artifact_type"
        case fileSizeBytes = "file_size_bytes"
        case isPublicPageEnabled = "is_public_page_enabled"
        case slug
        case title
    }

}

