//
// V0AvatarCandidateCreateResponseItems.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public typealias V0AvatarCandidateCreateResponseItems = [V0AvatarCandidateCreateResponseItem]