//
// V0AvatarCandidateCreateBulkParams.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public typealias V0AvatarCandidateCreateBulkParams = [V0AvatarCandidateCreateParams]