//
// V0BuildListAllResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0BuildListAllResponseModel: Codable {

    public var data: [V0BuildListAllResponseItemModel]?
    public var paging: V0PagingResponseModel?

    public init(data: [V0BuildListAllResponseItemModel]?, paging: V0PagingResponseModel?) {
        self.data = data
        self.paging = paging
    }


}

