//
// V0BuildTriggerParamsBuildParams.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0BuildTriggerParamsBuildParams: Codable {

    public var branch: String?
    public var branchDest: String?
    public var branchDestRepoOwner: String?
    public var branchRepoOwner: String?
    public var buildRequestSlug: String?
    public var commitHash: String?
    public var commitMessage: String?
    public var commitPaths: [V0CommitPaths]?
    public var diffUrl: String?
    public var environments: [V0BuildParamsEnvironment]?
    public var pullRequestAuthor: String?
    public var pullRequestHeadBranch: String?
    public var pullRequestId: JSONValue?
    public var pullRequestMergeBranch: String?
    public var pullRequestRepositoryUrl: String?
    public var skipGitStatusReport: Bool?
    public var tag: String?
    public var workflowId: String?

    public init(branch: String?, branchDest: String?, branchDestRepoOwner: String?, branchRepoOwner: String?, buildRequestSlug: String?, commitHash: String?, commitMessage: String?, commitPaths: [V0CommitPaths]?, diffUrl: String?, environments: [V0BuildParamsEnvironment]?, pullRequestAuthor: String?, pullRequestHeadBranch: String?, pullRequestId: JSONValue?, pullRequestMergeBranch: String?, pullRequestRepositoryUrl: String?, skipGitStatusReport: Bool?, tag: String?, workflowId: String?) {
        self.branch = branch
        self.branchDest = branchDest
        self.branchDestRepoOwner = branchDestRepoOwner
        self.branchRepoOwner = branchRepoOwner
        self.buildRequestSlug = buildRequestSlug
        self.commitHash = commitHash
        self.commitMessage = commitMessage
        self.commitPaths = commitPaths
        self.diffUrl = diffUrl
        self.environments = environments
        self.pullRequestAuthor = pullRequestAuthor
        self.pullRequestHeadBranch = pullRequestHeadBranch
        self.pullRequestId = pullRequestId
        self.pullRequestMergeBranch = pullRequestMergeBranch
        self.pullRequestRepositoryUrl = pullRequestRepositoryUrl
        self.skipGitStatusReport = skipGitStatusReport
        self.tag = tag
        self.workflowId = workflowId
    }

    public enum CodingKeys: String, CodingKey { 
        case branch
        case branchDest = "branch_dest"
        case branchDestRepoOwner = "branch_dest_repo_owner"
        case branchRepoOwner = "branch_repo_owner"
        case buildRequestSlug = "build_request_slug"
        case commitHash = "commit_hash"
        case commitMessage = "commit_message"
        case commitPaths = "commit_paths"
        case diffUrl = "diff_url"
        case environments
        case pullRequestAuthor = "pull_request_author"
        case pullRequestHeadBranch = "pull_request_head_branch"
        case pullRequestId = "pull_request_id"
        case pullRequestMergeBranch = "pull_request_merge_branch"
        case pullRequestRepositoryUrl = "pull_request_repository_url"
        case skipGitStatusReport = "skip_git_status_report"
        case tag
        case workflowId = "workflow_id"
    }

}

