//
// V0BuildLogChunkItemResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0BuildLogChunkItemResponseModel: Codable {

    public var chunk: String?
    public var position: Int?

    public init(chunk: String?, position: Int?) {
        self.chunk = chunk
        self.position = position
    }


}

