//
// V0BuildShowResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0BuildShowResponseModel: Codable {

    public var data: V0BuildResponseItemModel?

    public init(data: V0BuildResponseItemModel?) {
        self.data = data
    }


}

