//
// V0CommitPaths.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0CommitPaths: Codable {

    public var added: [String]?
    public var modified: [String]?
    public var removed: [String]?

    public init(added: [String]?, modified: [String]?, removed: [String]?) {
        self.added = added
        self.modified = modified
        self.removed = removed
    }


}

