//
// V0PlanDataModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0PlanDataModel: Codable {

    public var containerCount: Int?
    public var expiresAt: String?
    public var _id: String?
    public var name: String?
    public var price: String?

    public init(containerCount: Int?, expiresAt: String?, _id: String?, name: String?, price: String?) {
        self.containerCount = containerCount
        self.expiresAt = expiresAt
        self._id = _id
        self.name = name
        self.price = price
    }

    public enum CodingKeys: String, CodingKey { 
        case containerCount = "container_count"
        case expiresAt = "expires_at"
        case _id = "id"
        case name
        case price
    }

}

