//
// V0ProjectFileStorageListResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0ProjectFileStorageListResponseModel: Codable {

    public var data: [V0ProjectFileStorageResponseItemModel]?
    public var paging: V0PagingResponseModel?

    public init(data: [V0ProjectFileStorageResponseItemModel]?, paging: V0PagingResponseModel?) {
        self.data = data
        self.paging = paging
    }


}

