//
// V0ProjectFileStorageResponseItemModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0ProjectFileStorageResponseItemModel: Codable {

    public var downloadUrl: String?
    public var exposedMetaDatastore: String?
    public var isExpose: Bool?
    public var isProtected: Bool?
    public var processed: Bool?
    public var slug: String?
    public var uploadFileName: String?
    public var uploadFileSize: Int?
    public var uploadUrl: String?
    public var userEnvKey: String?

    public init(downloadUrl: String?, exposedMetaDatastore: String?, isExpose: Bool?, isProtected: Bool?, processed: Bool?, slug: String?, uploadFileName: String?, uploadFileSize: Int?, uploadUrl: String?, userEnvKey: String?) {
        self.downloadUrl = downloadUrl
        self.exposedMetaDatastore = exposedMetaDatastore
        self.isExpose = isExpose
        self.isProtected = isProtected
        self.processed = processed
        self.slug = slug
        self.uploadFileName = uploadFileName
        self.uploadFileSize = uploadFileSize
        self.uploadUrl = uploadUrl
        self.userEnvKey = userEnvKey
    }

    public enum CodingKeys: String, CodingKey { 
        case downloadUrl = "download_url"
        case exposedMetaDatastore = "exposed_meta_datastore"
        case isExpose = "is_expose"
        case isProtected = "is_protected"
        case processed
        case slug
        case uploadFileName = "upload_file_name"
        case uploadFileSize = "upload_file_size"
        case uploadUrl = "upload_url"
        case userEnvKey = "user_env_key"
    }

}

