//
// V0ProvProfileDocumentUpdateParams.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0ProvProfileDocumentUpdateParams: Codable {

    public var isExpose: Bool?
    public var isProtected: Bool?
    public var processed: Bool?

    public init(isExpose: Bool?, isProtected: Bool?, processed: Bool?) {
        self.isExpose = isExpose
        self.isProtected = isProtected
        self.processed = processed
    }

    public enum CodingKeys: String, CodingKey { 
        case isExpose = "is_expose"
        case isProtected = "is_protected"
        case processed
    }

}

