//
// V0UserProfileDataModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0UserProfileDataModel: Codable {

    public var avatarUrl: String?
    public var email: String?
    public var isChatAvailable: Bool?
    public var slug: String?
    public var unconfirmedEmail: String?
    public var username: String?

    public init(avatarUrl: String?, email: String?, isChatAvailable: Bool?, slug: String?, unconfirmedEmail: String?, username: String?) {
        self.avatarUrl = avatarUrl
        self.email = email
        self.isChatAvailable = isChatAvailable
        self.slug = slug
        self.unconfirmedEmail = unconfirmedEmail
        self.username = username
    }

    public enum CodingKeys: String, CodingKey { 
        case avatarUrl = "avatar_url"
        case email
        case isChatAvailable = "is_chat_available"
        case slug
        case unconfirmedEmail = "unconfirmed_email"
        case username
    }

}

