//
// V0WebhookDeliveryItemResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V0WebhookDeliveryItemResponseModel: Codable {

    public var createdAt: String?
    public var requestHeaders: String?
    public var requestPayload: String?
    public var requestUrl: String?
    public var responseBody: String?
    public var responseHeaders: String?
    public var responseHttpStatus: String?
    public var responseSeconds: String?
    public var slug: String?
    public var updatedAt: String?

    public init(createdAt: String?, requestHeaders: String?, requestPayload: String?, requestUrl: String?, responseBody: String?, responseHeaders: String?, responseHttpStatus: String?, responseSeconds: String?, slug: String?, updatedAt: String?) {
        self.createdAt = createdAt
        self.requestHeaders = requestHeaders
        self.requestPayload = requestPayload
        self.requestUrl = requestUrl
        self.responseBody = responseBody
        self.responseHeaders = responseHeaders
        self.responseHttpStatus = responseHttpStatus
        self.responseSeconds = responseSeconds
        self.slug = slug
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey { 
        case createdAt = "created_at"
        case requestHeaders = "request_headers"
        case requestPayload = "request_payload"
        case requestUrl = "request_url"
        case responseBody = "response_body"
        case responseHeaders = "response_headers"
        case responseHttpStatus = "response_http_status"
        case responseSeconds = "response_seconds"
        case slug
        case updatedAt = "updated_at"
    }

}

